import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { base44 } from "@/api/base44Client";
import { Users, FileText, BookOpen, TrendingUp, ArrowUpRight, Activity, Mail, Database, Radio } from "lucide-react";

export default function AdminDashboard() {
  const [stats,setStats]=useState({newLeads:0,totalLeads:0,caseStudies:0,resources:0}); const [recentLeads,setRecentLeads]=useState([]); const [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{try{const [leads,studies,resources]=await Promise.all([base44.entities.Lead.list("-created_date",100),base44.entities.CaseStudy.list("-created_date",200),base44.entities.Resource.list("-created_date",200)]);setStats({newLeads:(leads||[]).filter(l=>l.status==="new").length,totalLeads:(leads||[]).length,caseStudies:(studies||[]).length,resources:(resources||[]).filter(r=>r.published).length});setRecentLeads((leads||[]).slice(0,6));}catch{}setLoading(false)})();},[]);
  return <div className="admin-dashboard"><div className="admin-page-head"><div><div className="admin-kicker">/ CONTROL ROOM</div><h1>OVERVIEW</h1><p>Manage your portfolio content, inbound leads and growth proof from one place.</p></div><div className="admin-live"><Radio /> CMS CONNECTED</div></div>
    <div className="dash-metrics"><DashStat icon={Users} value={stats.newLeads} label="NEW LEADS" tone="lime" /><DashStat icon={TrendingUp} value={stats.totalLeads} label="TOTAL LEADS" tone="blue" /><DashStat icon={FileText} value={stats.caseStudies} label="CASE STUDIES" tone="cyan" /><DashStat icon={BookOpen} value={stats.resources} label="PUBLISHED RESOURCES" tone="white" /></div>
    <div className="admin-board"><div className="board-heading"><div><span>LEAD FEED / RECENT</span><h2>INBOUND SIGNALS</h2></div><Link to="/admin/leads">OPEN LEADS <ArrowUpRight /></Link></div>{loading?<div className="admin-empty">LOADING SIGNALS...</div>:recentLeads.length===0?<div className="admin-empty">NO LEADS YET. YOUR NEXT CONTACT FORM SUBMISSION WILL APPEAR HERE.</div>:<div className="lead-table">{recentLeads.map((lead,i)=><div className="lead-row" key={lead.id}><span className="row-no">{String(i+1).padStart(2,"0")}</span><div className="lead-person"><strong>{lead.name||"Unknown"}</strong><small>{lead.email}</small></div><span className="lead-company">{lead.company||"—"}</span><StatusBadge status={lead.status}/><span className="lead-arrow">↗</span></div>)}</div>}</div>
    <div className="admin-shortcuts"><Link to="/admin/pages"><Database /><span><b>PAGE CMS</b><small>Edit page-level content</small></span><ArrowUpRight /></Link><Link to="/admin/case-studies"><FileText /><span><b>CASE STUDIES</b><small>Publish new proof</small></span><ArrowUpRight /></Link><Link to="/admin/settings"><Activity /><span><b>SITE SETTINGS</b><small>Profile, SEO & analytics</small></span><ArrowUpRight /></Link></div>
  </div>;
}
function DashStat({icon:Icon,value,label,tone}){return <div className={`dash-stat ${tone}`}><Icon/><strong>{value}</strong><span>{label}</span><small>LIVE</small></div>}
export function StatusBadge({status}){return <span className={`admin-status-badge ${status||"new"}`}>{(status||"new").replace("_"," ")}</span>}
